#!/bin/bash
0-current_working_directory*.0-current_working_directory.swp100-lets_move*.100-lets_move.swp101-clean_emacs*102-tree*103-commas10-back*11-lists*12-file_type*13-symbolic_link*14-copy_html*1-listit*2-bring_me_home*3-listfiles*4-listmorefiles*5-listfilesdigitonly*6-firstdirectory*7-movethatfile*8-firstdelete*9-firstdirdeletion*.9-firstdirdeletion.swpREADME.m
